---
- name: Playbook ansible vault
  hosts: localhost


  tasks:

    - name: bloque tareas configuracion certificado para IIS
      block:
      
        - name: Mostrar resultados
          debug:
            msg: "IIS"

      when: "'IIS' in hardening_tipo_servicio"

    - name: bloque tareas configuracion certificado para SQL
      block:

        - name: Mostrar resultados
          debug:
            msg: "SQL"

      when: "'SQL' in hardening_tipo_servicio"
