---
- name: Playbook ansible vault
  hosts: localhost
  vars_files:
    - credentials.yaml

  tasks:

    - name: prueba
      set_fact:
        prueba: "{{ clave_prueba }}"
      no_log: true

    - name: prueba variable
      debug:
        msg: "{{ clave_prueba }}"
